version: '3'

networks:
   docknet:
      driver: bridge
      ipam:
         config:
            - subnet: 172.20.0.0/16
              gateway: 172.20.0.1

volumes:
  pgdata:

services:
   db:
      image: postgres:latest
      container_name: postgres
      restart: always
      environment:
         - POSTGRES_USER=admin 
         - POSTGRES_PASSWORD=admin123
      volumes:
         - ./pgdata:/var/lib/postgresql/data
      networks:
         docknet:
            ipv4_address: 172.20.0.20

   nodejs:
      image: my-nodejs:latest
      container_name: my-nodejs
      restart: always
      networks:
         docknet:
            ipv4_address: 172.20.0.30

   webserver:
      image: nginx:stable-alpine
      container_name: webserver
      restart: unless-stopped
      ports: 
         - "80:80"
      volumes:
         - ./nginx:/etc/nginx/conf.d
      networks: 
         docknet:
            ipv4_address: 172.20.0.10
